# .codecov.yml
coverage:
  status:
    project:
      threshold: 1

# Configure how to upload coverage reports
upload:
  # The URL where reports will be uploaded
  url: 'https://codecov.io'
  file:
    - 'Calculator/Cobertura.xml'

