version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: win/default
    steps:
      - checkout
      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore Project1/Project1.csproj
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build Calculator/GraphInterface/GraphInterface.csproj --configuration Release

workflows:
  build_and_test:
    jobs:
      - build
