version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore Calculator/GraphInterface/GraphInterface.csproj
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test Calculator/GraphInterface/GraphInterface.csproj -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
          
  build:
    description: Build application with Release configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build Calculator/GraphInterface/GraphInterface.csproj --configuration Release

workflows:
  build_and_test:
    jobs:
      - build
      - test
