version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build "C:\Users\KaterynaDanylchenko\Desktop\circleciTestProject\Automated-Testing\Calculator\Calculator_Exam_CommandProject.sln" --configuration Release

workflows:
  build_and_test:
    jobs:
      - build
