version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  test:
    description: Setup and run application tests
    #parallelism: 4
    executor:
      name: win/server-2022
          
    steps:
      - checkout
      
      - run:
          name: Print current directory
          command: pwd
          
      - attach_workspace:
          at: .
      - run:
          name: "Run Application Tests"
          command: |
            #msbuild "Calculator/Tests/AnalizerClassLibrary.Tests.csproj" /p:Configuration=Release
             
            #circleci tests glob "Calculator/Tests/**/*Tests.cs" | circleci tests split > C:\Users\circleci\project\Calculator\Tests\tests-to-run
            
            # Read the content of the file
            #$testFiles = cat C:\Users\circleci\project\Calculator\Tests\tests-to-run
            #$removePath="Calculator\"
            #foreach ($testFile in $testFiles) {
                    #$relativePath = $testFile.Substring($removePath.Length) -replace '\\', '.' -replace '\.cs$', ''
                    #$relativePath
                    #dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --filter $relativePath --configuration Release --no-build --logger "junit;LogFileName=test-results.xml"  
            #}
            #dotnet.exe test Calculator/Tests/AnalizerClassLibrary.Tests.csproj -v n --configuration Release --no-build --logger "junit;LogFileName=C:\Users\circleci\project\Calculator\Tests\TestResults\test-results.xml" 
            dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Release --no-build --logger "junit;LogFileName=test-results.xml" 
          when: always
          
      - run:
          name: View XML File Content
          command: |
            cat Calculator\Tests\TestResults\test-results.xml

      - store_artifacts:
          path: Calculator\Tests\TestResults\test-results.xml
          destination: test-results
    
      - store_test_results:
          path: Calculator\Tests\TestResults\test-results.xml
 
  build:
    description: Build application with Release configuration
    executor:
      name: win/server-2022
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Install project dependencies"
          command: nuget restore Calculator/Calculator_Exam_CommandProject.sln
      - run:
          name: "Build Application according to some given configuration"
          command: cmd.exe /c Calculator_Buiild.bat
      - persist_to_workspace:
          root: .    # Root directory to persist
          paths:
            - .nuget/
            - Calculator/
      

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
