version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test
      - run:
          name: "Print Working Directory"
          command: pwd
  build:
    description: Build application with Release configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build GraphInterface.csproj /p:Configuration=Release

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
