version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/default
    steps:
      - checkout
      # Install .NET Framework 4.7.2 targeting pack
      - run:
          name: Install .NET Framework 4.7.2 targeting pack
          command: |
            Invoke-WebRequest -Uri https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054531-Web.exe -OutFile NDP472-KB4054531-Web.exe
            Start-Process -FilePath NDP472-KB4054531-Web.exe -ArgumentList "/quiet /norestart" -Wait
      - run:
          name: Install .NET SDK 8.0.204
          command: |
            $ErrorActionPreference = "Stop"
            Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
            .\dotnet-install.ps1 -Channel 8.0 -Version 8.0.204
            $dotnetInstallDir = "$env:USERPROFILE\.dotnet"
            [System.Environment]::SetEnvironmentVariable('DOTNET_ROOT', $dotnetInstallDir, [System.EnvironmentVariableTarget]::Machine)
            [System.Environment]::SetEnvironmentVariable('PATH', "$dotnetInstallDir;$dotnetInstallDir\tools;$env:PATH", [System.EnvironmentVariableTarget]::Machine)
            dotnet --list-sdks
            dotnet --version

      - run:
          name: Print current directory
          command: pwd
      - run:
          name: Display .NET SDK version
          command: dotnet --version
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - run: nuget restore Calculator/Tests/AnalizerClassLibrary.Tests.csproj -SolutionDirectory ./
      - run:
          name: "Run Application Tests"
          command: dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Debug
          #dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Debug
          #.\packages\xunit.runner.console.2.8.1\tools\net472\xunit.console.exe Calculator\Tests\bin\Debug\Tests.dll
         # .\packages\xunit.runner.console.2.8.1\build\xunit.runner.console.props
      - store_artifacts:
          path: test-results/results.xml.txt
          destination: /test-results
      - store_test_results:
          path: test-results
      
          
  build:
    description: Build application with Debug configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: nuget restore Calculator/Calculator_Exam_CommandProject.sln
      - run:
          name: "Build Application according to some given configuration"
          command: msbuild Calculator/GraphInterface/GraphInterface.csproj -t:build

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
