version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Print current directory
          command: pwd
      - run:
          name: Display .NET SDK version
          command: dotnet --version
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      #- run:
      #    name: Create Test Results Directory
      #    command: mkdir -p C:\Users\circleci\project\test-results
      - run: nuget restore Calculator/Calculator_Exam_CommandProject.sln
      - run:
          name: "Run Application Tests"
          command: |
            dotnet build Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Debug
            dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Debug --logger "trx;LogFileName=C:\Users\circleci\project\test-results\TestResults.trx"
          when: always
          #.\packages\xunit.runner.console.2.8.1\tools\net472\xunit.console.exe C:\Users\circleci\project\Calculator\Tests\bin\Debug\Tests.dll
          #dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Debug
          #.\packages\xunit.runner.console.2.8.1\tools\net472\xunit.console.exe Calculator\Tests\bin\Debug\Tests.dll
      - run:
          name: Convert TRX to JUnit
          command: trx2junit C:\Users\circleci\project\test-results\TestResults.trx -o C:\Users\circleci\project\test-results
      - run:
          name: List Test Results Directory
          command: dir C:\Users\circleci\project\test-results
      - store_test_results:
          path: C:\Users\circleci\project\test-results
          when: always
      
          
  build:
    description: Build application with Debug configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: nuget restore Calculator/Calculator_Exam_CommandProject.sln
      - run:
          name: "Build Application according to some given configuration"
          command: |
            dotnet build Calculator/GraphInterface/GraphInterface.csproj --configuration Debug
            dotnet build Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Debug
          #msbuild Calculator/GraphInterface/GraphInterface.csproj -t:build
      

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
