version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    parallelism: 4
    executor:
      name: win/default
    steps:
      - checkout
      
      - run:
          name: Print current directory
          command: pwd
      
      - run:
          name: Display .NET SDK version
          command: dotnet --version
      
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
    
      - run: nuget restore Calculator/Calculator_Exam_CommandProject.sln
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
     
      - run:
          name: "Run Application Tests"
          command: |
            dotnet build Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Release
             
            circleci tests glob "Calculator/Tests/**/*Tests.cs" | circleci tests split > C:\Users\circleci\project\Calculator\Tests\tests-to-run
            
            # Read the content of the file
            $testFiles = cat C:\Users\circleci\project\Calculator\Tests\tests-to-run
            $removePath="Calculator\"
            foreach ($testFile in $testFiles) {
                    $relativePath = $testFile.Substring($removePath.Length) -replace '\\', '.' -replace '\.cs$', ''
                    $relativePath
                    dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --filter $relativePath --configuration Release --no-build --logger "junit;LogFileName=test-results.xml"  
            }

           # dotnet test Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Release --no-build --logger "junit;LogFileName=C:\Users\circleci\project\Calculator\Tests\TestResults\test-results.xml" 
          when: always
          
      - run:
          name: View XML File Content
          command: |
            cat Calculator\Tests\TestResults\test-results.xml

      - store_artifacts:
          path: Calculator\Tests\TestResults\test-results.xml
          destination: test-results
    
      - store_test_results:
          path: Calculator\Tests\TestResults\test-results.xml
          
  build:
    description: Build application with Release configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: nuget restore Calculator/Calculator_Exam_CommandProject.sln
      - run:
          name: "Build Application according to some given configuration"
          command: |
            dotnet build Calculator/Tests/AnalizerClassLibrary.Tests.csproj --configuration Release
      

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
