version: 2.1

orbs:
  win: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Calculator/GraphInterface/GraphInterface.csproj" }}
      - run: nuget restore Calculator/Tests/AnalizerClassLibrary.Tests.csproj -SolutionDirectory ./
      - run: msbuild Calculator/Tests/AnalizerClassLibrary.Tests.csproj /t:restore
      - run: msbuild Calculator/Tests/AnalizerClassLibrary.Tests.csproj /p:Configuration=Debug
      - run: mono --debug ./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe Tests/bin/Debug/Tests.dll
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: test-results/results.xml.txt
          destination: /test-results
      - store_test_results:
          path: test-results
      
          
  build:
    description: Build application with Debug configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore Calculator/GraphInterface/GraphInterface.csproj --verbosity detailed
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build Calculator/GraphInterface/GraphInterface.csproj --configuration Debug

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
